# Set the name of your application:
APPLICATION = simple-app

# If no BOARD is found in the environment, use this default:
# BOARD ?= nucleo-f401re
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../riot
include $(RIOTBASE)/Makefile.include
